# Generated by Django 4.1.2 on 2022-11-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_comment_comment_notes_comme_created_3376bc_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=255),
        ),
    ]
