# Generated by Django 4.1.2 on 2022-11-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-publish']},
        ),
    ]
