# Generated by Django 4.1.2 on 2022-11-03 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['publish']},
        ),
    ]
