# Generated by Django 4.1.2 on 2022-11-30 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0007_note_users_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='users_liked',
        ),
        migrations.AddField(
            model_name='note',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='notes_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
